---
exclude_paths:
  - "vendor/"

plugins:
  fixme:
    enabled: true
  
  duplication:
    enabled: true
    config:
      languages:
        - php
  
  phpcodesniffer:
    enabled: true

  phpmd:
    enabled: true

  sonar-php:
    enabled: true
...